from dataclasses import dataclass, field

from pydantic import ValidationError

from app.schemas.library import RecipeDiscoveryRequest
from app.schemas.recipe_candidate import RecipeCandidate
from app.services.constraint_engine import contains_allergen
from app.services.recipe_image_service import placeholder_image_url
from app.utils.ingredient_normalizer import ingredient_matches, normalize_ingredient


@dataclass
class CandidateValidationResult:
    valid_candidates: list[RecipeCandidate] = field(default_factory=list)
    failed_candidates: list[dict] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)


class RecipeValidationService:
    def validate_candidates(
        self,
        candidates: list[RecipeCandidate | dict],
        request: RecipeDiscoveryRequest | None = None,
    ) -> CandidateValidationResult:
        result = CandidateValidationResult()
        for raw in candidates:
            candidate, error = self._coerce(raw)
            if error:
                result.failed_candidates.append(error)
                continue
            assert candidate is not None
            errors, warnings = self._validate(candidate, request)
            if errors:
                result.failed_candidates.append(
                    {
                        "candidate_id": candidate.candidate_id,
                        "title": candidate.title,
                        "errors": errors,
                    }
                )
                continue
            if not candidate.image_url and not candidate.image_path:
                candidate = candidate.model_copy(
                    update={
                        "image_url": placeholder_image_url(
                            candidate.title, candidate.cuisine, candidate.meal_type
                        )
                    }
                )
            merged_warnings = [*candidate.validation_warnings, *warnings]
            candidate = candidate.model_copy(
                update={"validation_warnings": list(dict.fromkeys(merged_warnings))}
            )
            result.valid_candidates.append(candidate)
            result.warnings.extend(f"{candidate.title}: {warning}" for warning in warnings)
        return result

    def _coerce(self, raw: RecipeCandidate | dict) -> tuple[RecipeCandidate | None, dict | None]:
        try:
            return RecipeCandidate.model_validate(raw), None
        except ValidationError as exc:
            return None, {"candidate_id": None, "title": None, "errors": [str(exc)]}

    def _validate(
        self, candidate: RecipeCandidate, request: RecipeDiscoveryRequest | None
    ) -> tuple[list[str], list[str]]:
        errors: list[str] = []
        warnings: list[str] = []
        if not candidate.title.strip():
            errors.append("Missing title")
        if len(candidate.ingredients) < 3:
            errors.append("Too few ingredients")
        if len(candidate.instructions) < 2:
            errors.append("Too few instruction steps")
        if candidate.cook_time_min is None:
            warnings.append("Missing cook time")
        if request and request.max_cook_time_min and candidate.cook_time_min:
            if candidate.cook_time_min > request.max_cook_time_min:
                errors.append("Exceeds requested maximum cook time")
        if len(candidate.ingredients) > 18:
            warnings.append("Long ingredient list; may be less home-cookable")
        if len(candidate.instructions) > 12:
            warnings.append("Many instruction steps; may be complex")
        if not candidate.equipment:
            warnings.append("Equipment not specified")
        if not all(
            value is not None
            for value in [
                candidate.calories,
                candidate.protein_g,
                candidate.carbs_g,
                candidate.fat_g,
                candidate.fiber_g,
            ]
        ):
            warnings.append("Nutrition metadata is incomplete or estimated")
        if candidate.source_type == "ai_generated":
            warnings.append("Nutrition is an estimate generated by an AI model")

        recipe = candidate.to_recipe(request.user_id if request else "validation")
        if request and contains_allergen(recipe, request.allergies):
            errors.append("Contains requested allergy")
        if request and self._contains_blocked_ingredient(
            recipe.ingredients,
            request.excluded_ingredients,
        ):
            errors.append("Contains excluded ingredient")
        if (
            request
            and request.diet_type
            and self._violates_requested_diet(candidate, request.diet_type)
        ):
            errors.append(f"Does not satisfy requested diet type: {request.diet_type}")
        return errors, warnings

    def _contains_blocked_ingredient(self, ingredients: list[str], blocked: list[str]) -> bool:
        return any(
            ingredient_matches(item, ingredient)
            for item in blocked
            for ingredient in ingredients
        )

    def _violates_requested_diet(self, candidate: RecipeCandidate, diet_type: str) -> bool:
        requested = diet_type.lower()
        tags = {tag.lower() for tag in candidate.diet_tags}
        allergens = {normalize_ingredient(item).lower() for item in candidate.allergens}
        if requested == "dairy-free":
            return "dairy" in allergens
        if requested == "gluten-free":
            return "gluten" in allergens
        if requested in {"vegetarian", "vegan", "high-protein"}:
            return requested not in tags
        return False
