from dataclasses import dataclass, field

from pydantic import ValidationError

from app.schemas.library import RecipeDiscoveryRequest
from app.schemas.recipe import Recipe
from app.schemas.recipe_candidate import RecipeCandidate
from app.schemas.user import NO_RESTRICTION_DIET_TYPES
from app.services.constraint_engine import contains_allergen, violates_diet_type
from app.utils.ingredient_normalizer import ingredient_matches


@dataclass
class CandidateValidationResult:
    valid_candidates: list[RecipeCandidate] = field(default_factory=list)
    failed_candidates: list[dict] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)


class RecipeValidationService:
    def validate_candidates(
        self,
        candidates: list[RecipeCandidate | dict],
        request: RecipeDiscoveryRequest | None = None,
    ) -> CandidateValidationResult:
        result = CandidateValidationResult()
        for raw in candidates:
            candidate, error = self._coerce(raw)
            if error:
                result.failed_candidates.append(error)
                continue
            assert candidate is not None
            errors, warnings = self._validate(candidate, request)
            if errors:
                result.failed_candidates.append(
                    {
                        "candidate_id": candidate.candidate_id,
                        "title": candidate.title,
                        "errors": errors,
                    }
                )
                continue
            # `image_url`/`image_path` are deliberately left unset when the
            # candidate didn't already have one (ROADMAP 4.4 quick fix): this
            # used to synthesize a `placehold.co` URL server-side -- a remote
            # network call baked into every card. The frontend now renders
            # zero-network deterministic local art
            # (`web/src/components/RecipeArt.tsx`) whenever both are absent,
            # so there is nothing for this service to fill in.
            merged_warnings = [*candidate.validation_warnings, *warnings]
            candidate = candidate.model_copy(
                update={"validation_warnings": list(dict.fromkeys(merged_warnings))}
            )
            result.valid_candidates.append(candidate)
            result.warnings.extend(f"{candidate.title}: {warning}" for warning in warnings)
        return result

    def _coerce(self, raw: RecipeCandidate | dict) -> tuple[RecipeCandidate | None, dict | None]:
        try:
            return RecipeCandidate.model_validate(raw), None
        except ValidationError as exc:
            return None, {"candidate_id": None, "title": None, "errors": [str(exc)]}

    def _validate(
        self, candidate: RecipeCandidate, request: RecipeDiscoveryRequest | None
    ) -> tuple[list[str], list[str]]:
        errors: list[str] = []
        warnings: list[str] = []
        if not candidate.title.strip():
            errors.append("Missing title")
        if len(candidate.ingredients) < 3:
            errors.append("Too few ingredients")
        if len(candidate.instructions) < 2:
            errors.append("Too few instruction steps")
        if candidate.cook_time_min is None:
            warnings.append("Missing cook time")
        if request and request.max_cook_time_min and candidate.cook_time_min:
            if candidate.cook_time_min > request.max_cook_time_min:
                errors.append("Exceeds requested maximum cook time")
        if len(candidate.ingredients) > 18:
            warnings.append("Long ingredient list; may be less home-cookable")
        if len(candidate.instructions) > 12:
            warnings.append("Many instruction steps; may be complex")
        if not candidate.equipment:
            warnings.append("Equipment not specified")
        if not all(
            value is not None
            for value in [
                candidate.calories,
                candidate.protein_g,
                candidate.carbs_g,
                candidate.fat_g,
                candidate.fiber_g,
            ]
        ):
            warnings.append("Nutrition metadata is incomplete or estimated")
        if candidate.source_type == "ai_generated":
            warnings.append("Nutrition is an estimate generated by an AI model")

        # This Recipe is a throwaway used only to run the allergen/diet checks
        # below -- it is never persisted, so the owner id here is a fixed
        # placeholder, not the real caller's user id (which the wire request
        # no longer even carries; see app/schemas/library.py).
        recipe = candidate.to_recipe("candidate-validation")
        if request and contains_allergen(recipe, request.allergies):
            errors.append("Contains requested allergy")
        if request and self._contains_blocked_ingredient(
            [item.name for item in recipe.ingredients],
            request.excluded_ingredients,
        ):
            errors.append("Contains excluded ingredient")
        if (
            request
            and request.diet_type
            and self._violates_requested_diet(recipe, candidate, request.diet_type)
        ):
            errors.append(f"Does not satisfy requested diet type: {request.diet_type}")
        return errors, warnings

    def _contains_blocked_ingredient(self, ingredients: list[str], blocked: list[str]) -> bool:
        return any(
            ingredient_matches(item, ingredient)
            for item in blocked
            for ingredient in ingredients
        )

    def _violates_requested_diet(
        self, recipe: Recipe, candidate: RecipeCandidate, diet_type: str
    ) -> bool:
        requested = diet_type.lower()
        if requested in NO_RESTRICTION_DIET_TYPES:
            return False
        # dairy-free/gluten-free are routed through contains_allergen -- the
        # same deterministic substring-matching safety authority
        # constraint_engine.violates_diet_type itself uses -- rather than a
        # second, weaker opinion built from the candidate's stored
        # `allergens` labels. Those labels come from derive_allergen_labels'
        # exact-set matching, which misses compound ingredient names (e.g.
        # "buttermilk", "all-purpose flour"); relying on them here was the
        # exact leak constraint_engine's diet-leak fix (commit 6c89292)
        # already closed for its own diet check. See
        # tests/test_recipe_validation_service.py's leak-closed regression
        # tests for the real corpus recipes that demonstrated this gap.
        if requested == "dairy-free":
            return contains_allergen(recipe, ["dairy"])
        if requested == "gluten-free":
            return contains_allergen(recipe, ["gluten"])
        # vegetarian/vegan: the tag requirement is a TIGHTENING, not the
        # sole check -- diet_014 (adjudication_20260718T090522Z.md) proved a
        # self-asserted tag can be falsified by the recipe's own ingredients
        # (r_004, tagged "vegetarian", carried a bare `parmesan` row).
        # constraint_engine.violates_diet_type's tag opt-out was removed for
        # exactly this reason; this call site must not reintroduce the same
        # gap by trusting the tag alone. A candidate must BOTH carry the
        # requested tag AND pass the engine's deterministic exclusion-
        # vocabulary scan -- either condition failing is a violation.
        # high-protein has no engine-side exclusion vocabulary (it is a
        # nutrition-content label, not a diet restriction the engine
        # enforces), so it remains tag-only.
        tags = {tag.lower() for tag in candidate.diet_tags}
        if requested in {"vegetarian", "vegan"}:
            return requested not in tags or violates_diet_type(recipe, requested)
        if requested == "high-protein":
            return requested not in tags
        # Fail closed: an unrecognized diet_type (e.g. "pescatarian",
        # "kosher", "halal", a typo) must never fall through to `return
        # False` here -- False means "does not violate", which `_validate`'s
        # caller reads as ADMIT. That is exactly the fail-open bug
        # constraint_engine.violates_diet_type's own comment warns against
        # ("Returning False would silently claim the recipe is safe for that
        # diet; fail loudly instead"); mirrored here rather than duplicated
        # as a second, independently-drifting rule. Confirmed live by the
        # adversarial safety benchmark's multi_015/multi_025/diet_040 cases
        # (see docs/BACKLOG.md's "Unknown diet_type fails OPEN" entry).
        raise ValueError(
            f"_violates_requested_diet does not enforce diet_type {diet_type!r}. "
            "Supported: vegetarian, vegan, high-protein (tag-based), "
            "dairy-free, gluten-free (allergen-based), plus no-restriction "
            f"aliases {sorted(NO_RESTRICTION_DIET_TYPES)}."
        )
