import json
import re
from typing import Any
from uuid import uuid4

from app.config import get_settings
from app.schemas.library import RecipeDiscoveryRequest
from app.schemas.recipe_candidate import RecipeCandidate
from app.services.model_provider import _generate_text  # type: ignore[attr-defined]


class RecipeGenerationService:
    """LLM-backed recipe generation behind a strict schema boundary."""

    def generate(self, request: RecipeDiscoveryRequest) -> list[RecipeCandidate]:
        settings = get_settings()
        if settings.model_provider == "mock":
            return []

        prompt = self._prompt(request)
        text = _generate_text(settings.model_provider, prompt, settings)
        payload = self._extract_json(text)
        candidates: list[RecipeCandidate] = []
        for item in payload:
            item = self._sanitize_candidate_payload(dict(item))
            candidates.append(RecipeCandidate.model_validate(item))
        return candidates

    def _prompt(self, request: RecipeDiscoveryRequest) -> str:
        return f"""
Return strict JSON only: an array of recipe candidate objects compatible with this schema:
candidate_id, title, cuisine, meal_type, description, ingredients, instructions,
cook_time_min, difficulty, servings, calories, protein_g, carbs_g, fat_g, fiber_g,
allergens, diet_tags, equipment, image_url, source_type, source_name, home_cookable_score,
validation_warnings.

Create {request.count} home-cookable recipes.
Cuisines: {request.cuisines or ["Any"]}.
Meal type: {request.meal_type or "any"}.
Diet type: {request.diet_type or "none"}.
Max cook time minutes: {request.max_cook_time_min or "none"}.
Difficulty: {request.difficulty or "any"}.
Avoid allergens: {request.allergies}.
Avoid ingredients: {request.excluded_ingredients}.
Extra preferences: {request.extra_preferences or "none"}.

Use quantified ingredients such as "150 g chicken breast" or "1 medium egg".
Avoid deep frying and restaurant-only equipment. Do not include medical claims.
Set source_type to "ai_generated". Mark nutrition as estimated in validation_warnings.
"""

    def _extract_json(self, text: str) -> list[dict[str, Any]]:
        data = self._decode_json_payload(text)
        if isinstance(data, dict) and "candidates" in data:
            data = data["candidates"]
        if isinstance(data, dict) and "recipes" in data:
            data = data["recipes"]
        if not isinstance(data, list):
            raise ValueError("Recipe generation did not return a JSON array.")
        return [item for item in data if isinstance(item, dict)]

    def _decode_json_payload(self, text: str) -> Any:
        candidates = [text.strip()]
        fenced_blocks = re.finditer(r"```(?:json)?\s*(.*?)```", text, re.S)
        candidates.extend(match.group(1).strip() for match in fenced_blocks)
        candidates.extend(self._json_substrings(text))

        last_error: Exception | None = None
        for candidate in candidates:
            if not candidate:
                continue
            try:
                return json.loads(candidate)
            except json.JSONDecodeError as exc:
                last_error = exc
        preview = text.strip().replace("\n", " ")[:240]
        raise ValueError(f"Recipe generation returned non-JSON content: {preview}") from last_error

    def _json_substrings(self, text: str) -> list[str]:
        decoder = json.JSONDecoder()
        snippets: list[str] = []
        for index, char in enumerate(text):
            if char not in "[{":
                continue
            try:
                _, end = decoder.raw_decode(text[index:])
            except json.JSONDecodeError:
                continue
            snippets.append(text[index : index + end])
        return snippets

    def _sanitize_candidate_payload(self, item: dict[str, Any]) -> dict[str, Any]:
        item.setdefault("candidate_id", f"llm_{uuid4().hex[:12]}")
        item["source_type"] = "ai_generated"
        item["ingredients"] = self._coerce_string_list(item.get("ingredients"))
        item["instructions"] = self._coerce_string_list(item.get("instructions"))
        item["allergens"] = self._coerce_string_list(item.get("allergens"))
        item["diet_tags"] = self._coerce_string_list(item.get("diet_tags"))
        item["equipment"] = self._coerce_string_list(item.get("equipment"))

        for field in [
            "cook_time_min",
            "servings",
            "calories",
            "protein_g",
            "carbs_g",
            "fat_g",
            "fiber_g",
        ]:
            item[field] = self._coerce_number(item.get(field))

        item["home_cookable_score"] = self._coerce_score(item.get("home_cookable_score"))
        warnings = self._coerce_string_list(item.get("validation_warnings"))
        if "Nutrition is an estimate generated by an AI model." not in warnings:
            warnings.append("Nutrition is an estimate generated by an AI model.")
        item["validation_warnings"] = warnings
        return item

    def _coerce_string_list(self, value: Any) -> list[str]:
        if value is None:
            return []
        if isinstance(value, str):
            separators = "\n" if "\n" in value else ","
            return [item.strip(" -\t") for item in value.split(separators) if item.strip(" -\t")]
        if isinstance(value, list):
            items: list[str] = []
            for item in value:
                if isinstance(item, dict):
                    quantity = item.get("quantity") or item.get("amount") or ""
                    unit = item.get("unit") or ""
                    name = item.get("name") or item.get("ingredient") or item.get("item") or ""
                    text = " ".join(str(part).strip() for part in [quantity, unit, name] if part)
                    if text:
                        items.append(text)
                elif item is not None:
                    items.append(str(item).strip())
            return [item for item in items if item]
        return [str(value).strip()] if str(value).strip() else []

    def _coerce_number(self, value: Any) -> float | int | None:
        if value is None or value == "":
            return None
        if isinstance(value, int | float):
            return value
        match = re.search(r"-?\d+(?:\.\d+)?", str(value))
        if not match:
            return None
        number = float(match.group())
        return int(number) if number.is_integer() else number

    def _coerce_score(self, value: Any) -> float:
        number = self._coerce_number(1.0 if value is None else value)
        if number is None:
            return 1.0
        score = float(number)
        if score > 1 and score <= 10:
            score = score / 10
        elif score > 10:
            score = score / 100
        return max(0.0, min(1.0, score))
