/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api-info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Api Info */
        get: operations["api_info_api_info_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/inventory/extract": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Extract Inventory */
        post: operations["extract_inventory_inventory_extract_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recipes/{recipe_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Recipe
         * @description Public call: no session bootstrap, no rate limit -- this is a pure
         *     lookup by id into the already-loaded corpus (`app.services.
         *     recipe_retriever.get_recipe_by_id`), the same lookup POST /plan/day and
         *     friends already do server-side to resolve a `PlanItem.recipe_id` back to
         *     its full `Recipe`. It computes nothing (no nutrition math, no allergy
         *     decision) and makes no safety decision of its own -- it only returns
         *     already-computed, already-grounded data the frontend can't otherwise
         *     reach from a `PlanItem` (which only carries `{recipe_id, title,
         *     servings}`, see `app.schemas.day_plan.PlanItem`). Used by the day/week
         *     plan views' "click a recipe name" detail modal.
         */
        get: operations["get_recipe_recipes__recipe_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recipes/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Search Recipes
         * @description Deterministic search/filter over the existing static corpus (loaded
         *     via `app.rag.loaders.load_corpus`) -- NOT the generative `/library/
         *     discover` endpoint. Rate-limited the same way as POST /recipes/recommend
         *     and POST /recipes/instructions above (this file's existing pattern for a
         *     non-personalized-write, corpus-scale endpoint); see
         *     `require_recommend_rate_limit`'s own docstring. `session_user_id` is
         *     otherwise unused: this endpoint reads/writes no per-user data, exactly
         *     like /recipes/instructions.
         *
         *     SAFETY (mandatory, verifiable): allergen exclusion and diet-type
         *     exclusion are each decided by calling `app.services.constraint_engine`'s
         *     `contains_allergen`/`violates_diet_type` DIRECTLY -- the same
         *     deterministic, substring-matching primitives `validate_recipe` itself
         *     calls -- never an LLM, and never `recipe.allergens`/`recipe.diet_tags`
         *     tag metadata alone. `validate_recipe` itself is deliberately NOT used
         *     here: it also enforces `contains_disliked_ingredient`/
         *     `violates_cook_time`, which have no meaning for a search/browse request
         *     and would require synthesizing dummy values on a fake `UserProfile`.
         *
         *     Calorie/macro range filtering reads ONLY
         *     `app.services.nutrition_view.trusted_per_serving` -- never
         *     `recipe.calories`/`recipe.protein_g` (self-reported tag fields, never
         *     trusted for scoring/filtering per that model's own docstring). When at
         *     least one calorie/macro filter is supplied and `trusted_per_serving`
         *     returns `None` for a recipe (ungrounded/partial/flagged nutrition), that
         *     recipe is excluded and counted in `macro_unavailable_excluded`. When NO
         *     calorie/macro filter is supplied, nutrition groundedness is never
         *     checked and nothing is excluded on that basis -- a cuisine/allergen/diet
         *     -only search must not silently drop ungrounded recipes.
         *
         *     Cuisine matching mirrors `RecipeRetriever._keyword_score`'s existing
         *     convention (app.services.recipe_retriever): case-insensitive exact
         *     match against `recipe.cuisine`, not a substring/fuzzy match.
         *
         *     Linear scan over `load_corpus()`, no index/cache -- the same performance
         *     posture POST /plan/day, /plan/batch, and /plan/week already use
         *     (app.api.routes_day_planner) at this corpus size.
         */
        post: operations["search_recipes_recipes_search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recipes/recommend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Recommend Recipes */
        post: operations["recommend_recipes_recipes_recommend_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recipes/instructions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Get Detailed Instructions */
        post: operations["get_detailed_instructions_recipes_instructions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/library/discover": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Discover Recipes */
        post: operations["discover_recipes_library_discover_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/library/save": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Save Recipe Candidates */
        post: operations["save_recipe_candidates_library_save_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/library/reindex": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reindex Recipe Library */
        post: operations["reindex_recipe_library_library_reindex_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/library": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List User Recipe Library */
        get: operations["list_user_recipe_library_library_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/library/{recipe_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete User Recipe */
        delete: operations["delete_user_recipe_library__recipe_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Feedback */
        post: operations["post_feedback_feedback_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plan/day": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Plan Day
         * @description B3: macro-targeted day-plan assembly.
         *
         *     SAFETY (mandatory, verifiable): every recipe in the corpus is run
         *     through `app.services.constraint_engine.validate_recipe` -- the exact
         *     same deterministic check `app.graph.nodes.safety_filter_node` uses
         *     (app/graph/nodes.py:172-200) -- BEFORE `app.services.day_planner` ever
         *     sees it. Only the survivors (`safe_candidates`) are passed into
         *     `assemble_plan`/`assemble_day_plan`; rejected recipes are reported back
         *     (mirroring `safety_filter_node`'s own rejected_recipes bookkeeping) but
         *     never reach the planner. This is the sole point in this file where
         *     safety is decided, and it happens purely in deterministic code -- no LLM
         *     call anywhere on this path.
         *
         *     `request.inventory` (2026-07-22 pantry-tiebreak follow-up) is forwarded
         *     to `assemble_plan`/`assemble_day_plan` as `inventory=` -- this endpoint
         *     only ever exercises the pantry-coverage tiebreak (variety is a
         *     structural no-op here; there is no "prior day" for a single day-plan
         *     request -- see `app.services.day_planner`'s module docstring). It
         *     never changes which recipes are safety-cleared above, and never
         *     weakens the macro-fit primary sort.
         */
        post: operations["plan_day_plan_day_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plan/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Plan Batch
         * @description Phase 4 item 1: meal-prep batch solver -- pick 2-3 recipes, scale to
         *     N whole containers, each container individually hitting a per-container
         *     kcal/protein target, with one consolidated shopping list.
         *
         *     SAFETY (mandatory, verifiable, identical pattern to `plan_day` above):
         *     every recipe in the corpus is run through
         *     `app.services.constraint_engine.validate_recipe` BEFORE
         *     `app.services.batch_planner` ever sees it. Only the survivors
         *     (`safe_candidates`) are passed into `assemble_batch_plan`; rejected
         *     recipes are reported back in `rejected_recipes` but never reach the
         *     planner. This is the sole point in this file where safety is decided
         *     for this endpoint, and it happens purely in deterministic code -- no
         *     LLM call anywhere on this path.
         *
         *     The consolidated shopping list is built via
         *     `app.services.procurement_service.build_shopping_list_for_items`
         *     against the assembled `plan.items` and `request.inventory` -- the same
         *     combine-then-reconcile-once logic `plan_shopping_list` uses for a
         *     `DayPlan`, reused unmodified rather than reimplemented (see that
         *     function's docstring for the double-counting bug it avoids).
         */
        post: operations["plan_batch_plan_batch_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plan/week": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Plan Week
         * @description Phase 4 item 2: full weekly meal-plan solver -- a THIN COMPOSITION of
         *     B3 (`app.services.day_planner`), NOT a new solver. `request.days`
         *     independent calls to `assemble_day_plan` (same target every time, since
         *     macro selection is pantry-independent -- see
         *     `app.services.weekly_planner`'s module docstring), plus ONE consolidated
         *     shopping-list reconciliation across every day's `PlanItem`s pooled
         *     together.
         *
         *     SAFETY (mandatory, verifiable, identical pattern to `plan_day`/
         *     `plan_batch` above): every recipe in the corpus is run through
         *     `app.services.constraint_engine.validate_recipe` BEFORE
         *     `app.services.weekly_planner` ever sees it. Only the survivors
         *     (`safe_candidates`) are passed into `assemble_week`; rejected recipes
         *     are reported back in `rejected_recipes` but never reach the planner.
         *     This is the sole point in this file where safety is decided for this
         *     endpoint, and it happens purely in deterministic code -- no LLM call
         *     anywhere on this path.
         *
         *     THE SINGLE MOST CORRECTNESS-CRITICAL STEP: the consolidated shopping
         *     list is built by exactly ONE call to
         *     `app.services.procurement_service.build_shopping_list_for_items`, over
         *     every day's `PlanItem`s pooled into one flat list, with
         *     `request.inventory` reconciled EXACTLY ONCE -- never a naive
         *     per-day-then-merge composition, which would reintroduce the exact B4
         *     double-counting bug class (two days each individually "satisfied" by
         *     the same undepleted pantry, both shortfalls artificially zeroed). See
         *     `build_shopping_list_for_items`'s own docstring for the full
         *     explanation.
         */
        post: operations["plan_week_plan_week_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plan/shopping-list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Plan Shopping List
         * @description B4: shopping-list aggregation across an already-assembled DayPlan.
         *
         *     NOT a safety endpoint: `request.plan` was already safety-cleared by
         *     POST /plan/day (every recipe_id in `plan.items` passed
         *     constraint_engine.validate_recipe there); this endpoint does pure
         *     quantity arithmetic (app.services.procurement_service.
         *     build_shopping_list_for_plan) against the full corpus looked up by id,
         *     and makes no allergy/diet decision of its own -- see that function's
         *     docstring for the servings-scaling and merge logic.
         */
        post: operations["plan_shopping_list_plan_shopping_list_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tools/validate-recipe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Validate Recipe Tool
         * @description Direct pass-through to constraint_engine.validate_recipe -- runs every
         *     hard constraint (allergens, disliked ingredients, diet type, cook time)
         *     in the same order and returns the exact same ValidationResult a caller
         *     would get by importing and calling that function themselves.
         */
        post: operations["validate_recipe_tool_tools_validate_recipe_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tools/check-allergen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Check Allergen Tool
         * @description Direct pass-through to constraint_engine.contains_allergen.
         */
        post: operations["check_allergen_tool_tools_check_allergen_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tools/check-diet-violation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Check Diet Violation Tool
         * @description Direct pass-through to constraint_engine.violates_diet_type.
         *
         *     violates_diet_type raises ValueError for a diet_type it was never taught
         *     to enforce (see that function's docstring: it fails loudly rather than
         *     silently claiming a recipe is safe) -- surfaced here as 422, mirroring
         *     the existing ValueError->422 pattern in routes_day_planner.py, not
         *     swallowed or reinterpreted.
         */
        post: operations["check_diet_violation_tool_tools_check_diet_violation_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tools/derive-allergen-labels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Derive Allergen Labels Tool
         * @description Direct pass-through to constraint_engine.derive_allergen_labels.
         */
        post: operations["derive_allergen_labels_tool_tools_derive_allergen_labels_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/share": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Share Link
         * @description Builds the public snapshot via `app.services.share_service.
         *     create_share` -- the caller's own request object (a `Recipe`/`DayPlan`/
         *     `BatchPlan`/`WeeklyPlan` it already holds) is READ from, mapped through
         *     the server-side allowlist, and never persisted or echoed verbatim (see
         *     `share_service`'s module docstring, the load-bearing safety property of
         *     this whole feature). `user_id` is the verified session identity (see
         *     `app.dependencies.get_session_user`, which `require_share_create_rate_
         *     limit` itself depends on) -- never a client-supplied value.
         */
        post: operations["create_share_link_share_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/share/{share_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Share View
         * @description UNAUTHENTICATED by design. Returns 404 for BOTH a missing id and a
         *     revoked (`is_active=False`) one -- `app.services.share_service.
         *     get_share` already collapses those two cases into a single `None`, so
         *     there is no oracle here for "exists but was revoked" vs "never
         *     existed". Never returns the ORM row or `owner_user_id` -- only the
         *     `SharedPlanView` schema's own fields (`plan_type`, `content`,
         *     `disclaimer`), built from `SharedPlan.content` + `SharedPlan.plan_type`
         *     alone.
         */
        get: operations["get_share_view_share__share_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Mint Or Validate Session
         * @description Confirm an existing valid session (204, no Set-Cookie, no rotation)
         *     or mint a brand-new one (204 + Set-Cookie).
         *
         *     Reads BOTH possible existing-session carriers directly (never via
         *     `app.dependencies.get_session_user`, which enforces the CSRF header
         *     check this endpoint deliberately does not apply): the `X-Session-Token`
         *     header first, then the `mc_session` cookie -- an invalid/expired value
         *     on either is treated exactly like "absent" here (mint fresh), never as
         *     an error, since minting a new anonymous session is always a safe,
         *     always-available fallback for this endpoint.
         */
        post: operations["mint_or_validate_session_session_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * BatchPlan
         * @description Result of `app.services.batch_planner.assemble_batch_plan` (roadmap
         *     item: meal-prep batch solver, Phase 4 item 1). Deliberately NOT a
         *     repurposed `DayPlan` -- `DayPlan`'s `total_*`/`target_*` fields encode a
         *     SUMMED-vs-summed target (B3 semantics: many servings summed against one
         *     day-level target), while a `BatchPlan`'s fit is PER CONTAINER: every
         *     selected recipe's OWN per-serving macros must individually sit within
         *     tolerance of the per-container target. Jamming that into `DayPlan`
         *     would misrepresent the numbers, so this is a new, independent schema.
         *     See `app.services.batch_planner`'s module docstring for the full
         *     algorithm and the exact degenerate-case rules (0 eligible / 1 up to
         *     `min_recipes` eligible / >= `min_recipes` eligible, and an empty
         *     trusted pool).
         *
         *     `items` lists the selected recipes and how many whole containers each
         *     fills (`PlanItem.servings` is reused AS the container count for that
         *     recipe) -- container counts across `items` always sum to exactly
         *     `containers`, never a fractional split. `recipe_fits` carries the same
         *     selection's per-recipe fit detail (relative errors, per-serving
         *     macros) for display/debugging, aligned 1:1 with `items`.
         *
         *     `within_tolerance` is True iff every selected recipe was individually
         *     container-eligible (its own per-serving kcal AND protein each within
         *     the pre-registered +/-10%/+/-15% band of the per-container target,
         *     reused verbatim from `app.services.day_planner.DEFAULT_TOLERANCE`) --
         *     False only in the "0 eligible recipes, closest recipe used as an
         *     honest fallback" case (see module docstring); callers must check this
         *     flag explicitly rather than assume a non-empty `items` means the
         *     target was met.
         *
         *     `recipes_selected` can be LESS than the caller's requested
         *     `min_recipes` when fewer than `min_recipes` trusted recipes were
         *     container-eligible -- a real, distinct "recipe variety not achieved"
         *     signal (still `within_tolerance=True` per-container in that case), not
         *     an error condition; callers must check this explicitly too.
         */
        BatchPlan: {
            /** Items */
            items?: components["schemas"]["PlanItem"][];
            /** Containers */
            containers: number;
            /** Per Container Target Calories */
            per_container_target_calories: number;
            /** Per Container Target Protein G */
            per_container_target_protein_g: number;
            /** Recipes Selected */
            recipes_selected: number;
            /** Within Tolerance */
            within_tolerance: boolean;
            /** Trusted Pool Size */
            trusted_pool_size: number;
            /** Recipe Fits */
            recipe_fits?: components["schemas"]["RecipeFit"][];
        };
        /**
         * BatchPlanRequest
         * @description Wire contract for POST /plan/batch (meal-prep batch solver).
         *
         *     No `candidate_recipe_ids` field, deliberately -- same reasoning as
         *     `DayPlanRequest` (`app/schemas/day_plan.py`): the endpoint always
         *     starts from the full corpus and applies
         *     `app.services.constraint_engine.validate_recipe` itself (see
         *     `app.api.routes_day_planner.plan_batch`) -- letting a client hand in a
         *     pre-filtered candidate list would open a second, client-controlled
         *     path around that mandatory safety filter.
         *
         *     `inventory` mirrors `ShoppingListRequest.inventory`
         *     (`app/schemas/day_plan.py`) in shape, but is consumed differently: this
         *     endpoint builds the batch plan's ONE CONSOLIDATED shopping list itself
         *     (via `app.services.procurement_service.build_shopping_list_for_items`)
         *     as part of the same request/response round trip, rather than requiring
         *     a second call through POST /plan/shopping-list (which only accepts a
         *     `DayPlan`, not a `BatchPlan`) -- see `app.api.routes_day_planner.
         *     plan_batch`. Defaults to empty (no pantry reconciliation, full
         *     quantities listed) when omitted.
         */
        BatchPlanRequest: {
            user_profile: components["schemas"]["UserProfile"];
            /** Per Container Target Calories */
            per_container_target_calories: number;
            /** Per Container Target Protein G */
            per_container_target_protein_g: number;
            /**
             * Containers
             * @default 10
             */
            containers: number;
            /**
             * Min Recipes
             * @default 2
             */
            min_recipes: number;
            /**
             * Max Recipes
             * @default 3
             */
            max_recipes: number;
            /** Inventory */
            inventory?: components["schemas"]["ConfirmedIngredient"][];
        };
        /** BatchPlanResponse */
        BatchPlanResponse: {
            plan: components["schemas"]["BatchPlan"];
            /** Rejected Recipes */
            rejected_recipes?: components["schemas"]["RejectedRecipe"][];
            /** Shopping List */
            shopping_list?: components["schemas"]["ShoppingItem"][];
        };
        /** Body_extract_inventory_inventory_extract_post */
        Body_extract_inventory_inventory_extract_post: {
            /** Typed Ingredients */
            typed_ingredients?: string | null;
            /** Image */
            image?: string | null;
        };
        /** CheckAllergenToolRequest */
        CheckAllergenToolRequest: {
            recipe: components["schemas"]["Recipe"];
            /** Allergies */
            allergies?: string[];
        };
        /** CheckAllergenToolResponse */
        CheckAllergenToolResponse: {
            /** Contains Allergen */
            contains_allergen: boolean;
        };
        /** CheckDietViolationToolRequest */
        CheckDietViolationToolRequest: {
            recipe: components["schemas"]["Recipe"];
            /** Diet Type */
            diet_type: string;
        };
        /** CheckDietViolationToolResponse */
        CheckDietViolationToolResponse: {
            /** Violates Diet Type */
            violates_diet_type: boolean;
        };
        /** ConfirmedIngredient */
        ConfirmedIngredient: {
            /** Name */
            name: string;
            /** Quantity */
            quantity?: string | null;
            /** Amount */
            amount?: number | null;
            /** Unit */
            unit?: string | null;
            /** Purchase Date */
            purchase_date?: string | null;
            /**
             * Expires Soon
             * @default false
             */
            expires_soon: boolean;
        };
        /**
         * DayPlan
         * @description Result of app.services.day_planner.assemble_plan (or its
         *     assemble_day_plan / assemble_remaining_meal thin wrappers).
         *
         *     `items` lists the selected recipes and how many whole servings of each
         *     (multiplicity capped by `max_per_recipe` at assembly time). `meals_planned`
         *     is the actual number of recipe-servings assembled (== the requested K
         *     when a feasible combo existed; 0 when the enumerator could not build ANY
         *     combo of the requested size -- e.g. an empty trusted pool, or K exceeding
         *     `max_per_recipe * trusted_pool_size` -- never a padded or partial guess).
         *
         *     `within_tolerance` is the SOLE fit gate: True iff summed kcal is within
         *     the pre-registered +/-10% of target calories AND summed protein is
         *     within +/-15% of target protein_g (see
         *     app.services.day_planner.MacroTolerance). carbs/fat/fiber relative
         *     errors are reported for visibility only and never affect this flag (a
         *     deliberate v1 scope decision from the B3 design consult).
         *
         *     When nothing fits, the CLOSEST plan is still returned with
         *     within_tolerance=False -- callers must check this flag explicitly rather
         *     than assume a non-empty `items` means the target was met.
         */
        DayPlan: {
            /** Items */
            items?: components["schemas"]["PlanItem"][];
            /** Meals Planned */
            meals_planned: number;
            /** Trusted Pool Size */
            trusted_pool_size: number;
            /** Total Calories */
            total_calories: number;
            /** Total Protein G */
            total_protein_g: number;
            /** Total Carbs G */
            total_carbs_g: number;
            /** Total Fat G */
            total_fat_g: number;
            /** Total Fiber G */
            total_fiber_g: number;
            /** Target Calories */
            target_calories: number;
            /** Target Protein G */
            target_protein_g: number;
            /** Calories Relative Error */
            calories_relative_error: number;
            /** Protein Relative Error */
            protein_relative_error: number;
            /** Carbs Relative Error */
            carbs_relative_error?: number | null;
            /** Fat Relative Error */
            fat_relative_error?: number | null;
            /** Fiber Relative Error */
            fiber_relative_error?: number | null;
            /** Within Tolerance */
            within_tolerance: boolean;
            /** Pantry Coverage */
            pantry_coverage?: number | null;
        };
        /**
         * DayPlanRequest
         * @description Wire contract for POST /plan/day. `user_profile.macro_targets` is
         *     used directly as the assembly target -- for "remaining macros" mode the
         *     caller computes the remainder client-side (target minus what's already
         *     been eaten today) and puts it here; this endpoint holds no eaten-today
         *     state itself (see app.services.day_planner.assemble_remaining_meal's
         *     docstring).
         *
         *     No `candidate_recipe_ids` field, deliberately: the endpoint always
         *     starts from the full corpus and applies
         *     app.services.constraint_engine.validate_recipe itself (see
         *     app.api.routes_day_planner.plan_day) -- letting a client hand in a
         *     pre-filtered candidate list would open a second, client-controlled path
         *     around that mandatory safety filter.
         *
         *     `inventory` (2026-07-22 pantry-tiebreak follow-up) mirrors
         *     `WeeklyPlanRequest.inventory` in shape and purpose: it feeds
         *     `DayPlan.pantry_coverage`'s STRICT sub-macro tiebreak
         *     (`app.services.day_planner`'s module docstring) -- it never influences
         *     which recipes are safety-cleared or which macro target is used.
         *     Defaults to empty (no pantry reconciliation, pantry_coverage stays
         *     `None`) when omitted, a no-op preserving pre-existing behavior.
         */
        DayPlanRequest: {
            user_profile: components["schemas"]["UserProfile"];
            /** Meals */
            meals?: number | null;
            /**
             * Max Per Recipe
             * @default 2
             */
            max_per_recipe: number;
            /** Inventory */
            inventory?: components["schemas"]["ConfirmedIngredient"][];
        };
        /** DayPlanResponse */
        DayPlanResponse: {
            plan: components["schemas"]["DayPlan"];
            /** Rejected Recipes */
            rejected_recipes?: components["schemas"]["RejectedRecipe"][];
        };
        /** DeleteRecipeResponse */
        DeleteRecipeResponse: {
            /** Recipe Id */
            recipe_id: string;
            /** Deleted */
            deleted: boolean;
        };
        /** DeriveAllergenLabelsToolRequest */
        DeriveAllergenLabelsToolRequest: {
            /** Ingredient Names */
            ingredient_names?: string[];
        };
        /** DeriveAllergenLabelsToolResponse */
        DeriveAllergenLabelsToolResponse: {
            /** Allergens */
            allergens: string[];
        };
        /**
         * DetailedInstructionsRequest
         * @description Request to rewrite an already-shown recipe's terse instructions as
         *     detailed, beginner-friendly steps (phrasing/elaboration only -- see
         *     app.services.model_provider.generate_detailed_instructions_with_provider_chain).
         *
         *     `ingredients` are already-formatted display strings (e.g.
         *     "2 cups flour", the frontend's `ingredientDisplay(ingredient)` output),
         *     not structured `{name, amount, unit}` objects -- this is presentation-
         *     layer elaboration of a recipe already validated safe elsewhere, never a
         *     safety-relevant computation, so the wire contract doesn't need the
         *     structured Ingredient model here.
         */
        DetailedInstructionsRequest: {
            /** Title */
            title: string;
            /** Ingredients */
            ingredients?: string[];
            /** Instructions */
            instructions?: string[];
            /** Servings */
            servings?: number | null;
            /** Cuisine */
            cuisine?: string | null;
        };
        /**
         * DetailedInstructionsResponse
         * @description `generated=False` means `steps` is just the original `instructions`
         *     echoed back unmodified (no provider configured, or every provider
         *     failed/returned unparseable output) -- never fabricated detailed
         *     content. `provider_note` is set to a short human-readable explanation
         *     whenever `generated=False`, so the frontend can tell the user why the
         *     steps look unchanged rather than silently presenting them as if they
         *     were freshly elaborated.
         */
        DetailedInstructionsResponse: {
            /** Steps */
            steps?: string[];
            /** Generated */
            generated: boolean;
            /** Provider Note */
            provider_note?: string | null;
        };
        /** FeedbackRequest */
        FeedbackRequest: {
            /** Recipe Id */
            recipe_id: string;
            /**
             * Feedback Type
             * @enum {string}
             */
            feedback_type: "liked" | "disliked" | "cooked" | "skipped";
            /** Notes */
            notes?: string | null;
        };
        /**
         * FoodMacros
         * @description Macro nutrients per 100g of a food, as reported by USDA FDC.
         */
        FoodMacros: {
            /** Calories */
            calories: number;
            /** Protein G */
            protein_g: number;
            /** Carbs G */
            carbs_g: number;
            /** Fat G */
            fat_g: number;
            /** Fiber G */
            fiber_g: number;
        };
        /**
         * FoodMatch
         * @description A single FDC food matched for a normalized ingredient query.
         */
        FoodMatch: {
            /** Fdc Id */
            fdc_id: number;
            /** Description */
            description: string;
            /** Data Type */
            data_type: string;
            macros: components["schemas"]["FoodMacros"];
            /** Query */
            query: string;
        };
        /**
         * GroundingStatus
         * @description How much of a recipe's macros were derived from real ingredient data.
         *
         *     This is deliberately a first-class, explicit result rather than a bare
         *     number or `None` — a recipe with no grounded ingredients must never be
         *     mistaken for one that is genuinely low-calorie. Callers should branch on
         *     this before trusting `RecipeNutrition.total` / `per_serving`.
         * @enum {string}
         */
        GroundingStatus: "grounded" | "partial" | "ungrounded";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Ingredient */
        Ingredient: {
            /** Name */
            name: string;
            /** Amount */
            amount?: number | null;
            /** Unit */
            unit?: string | null;
            /** Preparation */
            preparation?: ("raw" | "cooked" | "canned") | null;
        };
        /**
         * IngredientContribution
         * @description The grounding outcome for a single recipe ingredient.
         */
        IngredientContribution: {
            /** Name */
            name: string;
            /** Grams */
            grams?: number | null;
            match?: components["schemas"]["FoodMatch"] | null;
            macros?: components["schemas"]["FoodMacros"] | null;
            /**
             * Grounded
             * @default false
             */
            grounded: boolean;
        };
        /** InventoryObservation */
        InventoryObservation: {
            /** Raw Name */
            raw_name: string;
            /** Normalized Name */
            normalized_name: string;
            /** Quantity */
            quantity?: string | null;
            /** Amount */
            amount?: number | null;
            /** Unit */
            unit?: string | null;
            /** Confidence */
            confidence: number;
            /**
             * Source
             * @enum {string}
             */
            source: "vision" | "text" | "manual";
            /**
             * Needs Confirmation
             * @default false
             */
            needs_confirmation: boolean;
        };
        /** MacroTargets */
        MacroTargets: {
            /** Calories */
            calories?: number | null;
            /** Protein G */
            protein_g?: number | null;
            /** Carbs G */
            carbs_g?: number | null;
            /** Fat G */
            fat_g?: number | null;
            /** Fiber G */
            fiber_g?: number | null;
        };
        /** MealRecommendation */
        MealRecommendation: {
            recipe: components["schemas"]["Recipe"];
            score: components["schemas"]["RecipeScore"];
            /** Explanation */
            explanation: string;
            /** Shopping List */
            shopping_list?: string[];
        };
        /**
         * PlanItem
         * @description One recipe's contribution to a DayPlan: how many whole servings of it
         *     were selected. v1 is whole-servings-only (roadmap item B3) -- no
         *     fractional/continuous portion scaling, which would make the +/-10%/
         *     +/-15% tolerance trivially satisfiable and gut the eval's meaning (see
         *     app.services.day_planner's module docstring and docs/BACKLOG.md for the
         *     continuous-scaling follow-up, which could reuse
         *     app.schemas.ingredient.scale_ingredients from roadmap item B2).
         */
        PlanItem: {
            /** Recipe Id */
            recipe_id: string;
            /** Title */
            title: string;
            /** Servings */
            servings: number;
        };
        /**
         * PublicBatchPlan
         * @description Share-safe projection of `app.schemas.batch_plan.BatchPlan`.
         *
         *     Excludes `trusted_pool_size` (same reasoning as `PublicDayPlan`).
         */
        PublicBatchPlan: {
            /** Items */
            items?: components["schemas"]["PlanItem"][];
            /** Containers */
            containers: number;
            /** Per Container Target Calories */
            per_container_target_calories: number;
            /** Per Container Target Protein G */
            per_container_target_protein_g: number;
            /** Recipes Selected */
            recipes_selected: number;
            /** Within Tolerance */
            within_tolerance: boolean;
            /** Recipe Fits */
            recipe_fits?: components["schemas"]["RecipeFit"][];
        };
        /**
         * PublicDayPlan
         * @description Share-safe projection of `app.schemas.day_plan.DayPlan`.
         *
         *     Excludes `trusted_pool_size` (leaks how many corpus recipes were
         *     available to the sharer, not a property of the plan itself).
         */
        PublicDayPlan: {
            /** Items */
            items?: components["schemas"]["PlanItem"][];
            /** Meals Planned */
            meals_planned: number;
            /** Total Calories */
            total_calories: number;
            /** Total Protein G */
            total_protein_g: number;
            /** Total Carbs G */
            total_carbs_g: number;
            /** Total Fat G */
            total_fat_g: number;
            /** Total Fiber G */
            total_fiber_g: number;
            /** Target Calories */
            target_calories: number;
            /** Target Protein G */
            target_protein_g: number;
            /** Calories Relative Error */
            calories_relative_error: number;
            /** Protein Relative Error */
            protein_relative_error: number;
            /** Carbs Relative Error */
            carbs_relative_error?: number | null;
            /** Fat Relative Error */
            fat_relative_error?: number | null;
            /** Fiber Relative Error */
            fiber_relative_error?: number | null;
            /** Within Tolerance */
            within_tolerance: boolean;
        };
        /**
         * PublicRecipe
         * @description Share-safe projection of `app.schemas.recipe.Recipe`.
         *
         *     Deliberately excludes (compare against the current `Recipe` field list
         *     in `app/schemas/recipe.py`): `owner_user_id` (the sharer's session
         *     identity -- THE headline leak this feature exists to prevent),
         *     `is_user_saved`, `image_path` (a server-local filesystem path),
         *     `is_active`, `restored_from_quarantine` (an internal display flag), and
         *     the SELF-REPORTED TAG MACROS `calories`/`protein_g`/`carbs_g`/`fat_g`/
         *     `fiber_g` (per `Recipe`'s own docstring, nothing should trust these
         *     directly -- only the grounded `nutrition` field is presentable).
         */
        PublicRecipe: {
            /** Recipe Id */
            recipe_id: string;
            /** Title */
            title: string;
            /** Cuisine */
            cuisine?: string | null;
            /** Meal Type */
            meal_type?: string | null;
            /** Ingredients */
            ingredients?: components["schemas"]["Ingredient"][];
            /** Instructions */
            instructions?: string[];
            /** Allergens */
            allergens?: string[];
            /** Diet Tags */
            diet_tags?: string[];
            /** Cook Time Min */
            cook_time_min?: number | null;
            nutrition?: components["schemas"]["RecipeNutrition"] | null;
            /** Description */
            description?: string | null;
            /** Difficulty */
            difficulty?: string | null;
            /** Servings */
            servings?: number | null;
            /** Equipment */
            equipment?: string[];
            /** Image Url */
            image_url?: string | null;
            /** Source Type */
            source_type?: string | null;
            /** Source Name */
            source_name?: string | null;
            /** Source Url */
            source_url?: string | null;
            /** Substitution Note */
            substitution_note?: string | null;
        };
        /**
         * PublicWeeklyPlan
         * @description Share-safe projection of `app.schemas.weekly_plan.WeeklyPlan`.
         *
         *     Excludes `trusted_pool_size` (same reasoning as `PublicDayPlan`) and
         *     `pantry_utilization`/`uncompared_ingredient_count` (both are
         *     pantry-derived and would leak "here's what's in the sharer's kitchen"
         *     to an anonymous viewer).
         */
        PublicWeeklyPlan: {
            /** Days */
            days?: components["schemas"]["PublicDayPlan"][];
        };
        /** Recipe */
        Recipe: {
            /** Recipe Id */
            recipe_id: string;
            /** Title */
            title: string;
            /** Cuisine */
            cuisine?: string | null;
            /** Meal Type */
            meal_type?: string | null;
            /** Ingredients */
            ingredients?: components["schemas"]["Ingredient"][];
            /** Instructions */
            instructions?: string[];
            /** Allergens */
            allergens?: string[];
            /** Diet Tags */
            diet_tags?: string[];
            /** Cook Time Min */
            cook_time_min?: number | null;
            /** Calories */
            calories?: number | null;
            /** Protein G */
            protein_g?: number | null;
            /** Carbs G */
            carbs_g?: number | null;
            /** Fat G */
            fat_g?: number | null;
            /** Fiber G */
            fiber_g?: number | null;
            nutrition?: components["schemas"]["RecipeNutrition"] | null;
            /** Description */
            description?: string | null;
            /** Difficulty */
            difficulty?: string | null;
            /**
             * Servings
             * @default 1
             */
            servings: number | null;
            /** Equipment */
            equipment?: string[];
            /** Image Url */
            image_url?: string | null;
            /** Image Path */
            image_path?: string | null;
            /**
             * Source Type
             * @default base
             */
            source_type: string | null;
            /** Source Name */
            source_name?: string | null;
            /** Source Url */
            source_url?: string | null;
            /** Owner User Id */
            owner_user_id?: string | null;
            /**
             * Is User Saved
             * @default false
             */
            is_user_saved: boolean;
            /**
             * Is Active
             * @default true
             */
            is_active: boolean;
            /**
             * Restored From Quarantine
             * @default false
             */
            restored_from_quarantine: boolean;
            /** Substitution Note */
            substitution_note?: string | null;
        };
        /** RecipeCandidate */
        RecipeCandidate: {
            /** Candidate Id */
            candidate_id: string;
            /** Title */
            title: string;
            /** Cuisine */
            cuisine?: string | null;
            /** Meal Type */
            meal_type?: string | null;
            /** Description */
            description?: string | null;
            /** Ingredients */
            ingredients?: components["schemas"]["Ingredient"][];
            /** Instructions */
            instructions?: string[];
            /** Cook Time Min */
            cook_time_min?: number | null;
            /** Difficulty */
            difficulty?: string | null;
            /**
             * Servings
             * @default 1
             */
            servings: number | null;
            /** Calories */
            calories?: number | null;
            /** Protein G */
            protein_g?: number | null;
            /** Carbs G */
            carbs_g?: number | null;
            /** Fat G */
            fat_g?: number | null;
            /** Fiber G */
            fiber_g?: number | null;
            /** Allergens */
            allergens?: string[];
            /** Diet Tags */
            diet_tags?: string[];
            /** Equipment */
            equipment?: string[];
            /** Image Url */
            image_url?: string | null;
            /** Image Path */
            image_path?: string | null;
            /**
             * Source Type
             * @enum {string}
             */
            source_type: "mock" | "ai_generated" | "external" | "curated" | "user_added";
            /** Source Name */
            source_name?: string | null;
            /** Source Url */
            source_url?: string | null;
            /**
             * Home Cookable Score
             * @default 1
             */
            home_cookable_score: number;
            /** Validation Warnings */
            validation_warnings?: string[];
        };
        /**
         * RecipeDiscoveryRequest
         * @description The `/library/discover` request body.
         *
         *     Deliberately has no `user_id` field: the caller's identity comes only
         *     from the verified session token (see app.dependencies.get_session_user),
         *     never from client-supplied request data. Route handlers thread the
         *     verified user id into the graph separately.
         */
        RecipeDiscoveryRequest: {
            /** Cuisines */
            cuisines?: string[];
            /** Meal Type */
            meal_type?: string | null;
            /** Diet Type */
            diet_type?: string | null;
            /** Max Cook Time Min */
            max_cook_time_min?: number | null;
            /** Difficulty */
            difficulty?: string | null;
            /**
             * Count
             * @default 10
             */
            count: number;
            /**
             * Home Cookable
             * @default true
             */
            home_cookable: boolean;
            /** Excluded Ingredients */
            excluded_ingredients?: string[];
            /** Allergies */
            allergies?: string[];
            /** Extra Preferences */
            extra_preferences?: string | null;
            /**
             * Source Mode
             * @default mock
             * @enum {string}
             */
            source_mode: "mock" | "llm" | "external" | "hybrid";
        };
        /** RecipeDiscoveryResponse */
        RecipeDiscoveryResponse: {
            /** Candidates */
            candidates?: components["schemas"]["RecipeCandidate"][];
            /** Debug Trace */
            debug_trace?: string[];
            /** Warnings */
            warnings?: string[];
            /** Errors */
            errors?: string[];
        };
        /**
         * RecipeFit
         * @description One selected recipe's fit against the batch plan's per-container
         *     macro target -- the public-facing projection of
         *     `app.services.batch_planner._container_eligible` for a recipe that
         *     ended up in `BatchPlan.items`. Display/debugging detail, not a second
         *     source of truth: `recipe_id` and `container_count` always line up 1:1
         *     with `BatchPlan.items` (same recipe_id, `container_count ==
         *     PlanItem.servings`) for the same `BatchPlan`.
         */
        RecipeFit: {
            /** Recipe Id */
            recipe_id: string;
            /** Title */
            title: string;
            /** Per Serving Calories */
            per_serving_calories: number;
            /** Per Serving Protein G */
            per_serving_protein_g: number;
            /** Kcal Relative Error */
            kcal_relative_error: number;
            /** Protein Relative Error */
            protein_relative_error: number;
            /** Container Count */
            container_count: number;
        };
        /**
         * RecipeNutrition
         * @description Computed macros for a recipe, with explicit grounding coverage.
         *
         *     `total` and `per_serving` only ever sum grounded contributions. When
         *     `status` is `PARTIAL`, they undercount the true recipe macros by
         *     whatever `ungrounded_ingredients` is missing — callers must check
         *     `status` (and/or `coverage`) before presenting these as authoritative.
         *
         *     `flags` holds trust-DEMOTING reason codes computed from this object's
         *     OWN computed values (e.g. an implausible per-serving kcal figure) --
         *     never from the recipe's self-reported tag macros, and never set by an
         *     LLM. A non-empty `flags` overrides `status` for trust purposes: see
         *     `app.services.nutrition_view.trusted_per_serving`/`macro_display_state`,
         *     the single chokepoint that enforces this, even for an otherwise
         *     `GROUNDED` recipe. Populated by `app.services.grounding_job.run_grounding`
         *     at grounding time, not by this schema itself.
         */
        RecipeNutrition: {
            status: components["schemas"]["GroundingStatus"];
            /** Servings */
            servings: number;
            total: components["schemas"]["FoodMacros"];
            per_serving: components["schemas"]["FoodMacros"];
            /** Contributions */
            contributions?: components["schemas"]["IngredientContribution"][];
            /** Ungrounded Ingredients */
            ungrounded_ingredients?: string[];
            /** Coverage */
            coverage: number;
            /** Flags */
            flags?: string[];
        };
        /** RecipeScore */
        RecipeScore: {
            /** Recipe Id */
            recipe_id: string;
            /** Pantry Match Score */
            pantry_match_score: number;
            /**
             * Pantry Mass Coverage
             * @default 0
             */
            pantry_mass_coverage: number;
            /** Macro Fit Score */
            macro_fit_score: number;
            /** Time Score */
            time_score: number;
            /** Preference Score */
            preference_score: number;
            /** Final Score */
            final_score: number;
            /** Missing Ingredients */
            missing_ingredients?: string[];
            /** Used Ingredients */
            used_ingredients?: string[];
            /** Rejection Reason */
            rejection_reason?: string | null;
        };
        /**
         * RecipeSearchRequest
         * @description The `POST /recipes/search` request body.
         *
         *     Deliberately standalone fields (mirroring `RecipeDiscoveryRequest` in
         *     app.schemas.library), not a synthesized `UserProfile` -- a search/browse
         *     context has no cook-time or disliked-ingredient semantics, so this
         *     schema does not invent dummy values for fields `UserProfile` requires
         *     but that don't apply here. This endpoint filters the existing static
         *     corpus (loaded via app.rag.loaders.load_corpus); it is NOT the
         *     generative `/library/discover` endpoint.
         */
        RecipeSearchRequest: {
            /** Cuisines */
            cuisines?: string[] | null;
            /** Allergies */
            allergies?: string[] | null;
            /** Diet Type */
            diet_type?: string | null;
            /** Calorie Min */
            calorie_min?: number | null;
            /** Calorie Max */
            calorie_max?: number | null;
            /** Protein Min */
            protein_min?: number | null;
            /** Protein Max */
            protein_max?: number | null;
            /** Carbs Min */
            carbs_min?: number | null;
            /** Carbs Max */
            carbs_max?: number | null;
            /** Fat Min */
            fat_min?: number | null;
            /** Fat Max */
            fat_max?: number | null;
            /**
             * Limit
             * @default 20
             */
            limit: number;
        };
        /** RecipeSearchResponse */
        RecipeSearchResponse: {
            /** Results */
            results?: components["schemas"]["Recipe"][];
            /**
             * Total Matched
             * @default 0
             */
            total_matched: number;
            /**
             * Macro Unavailable Excluded
             * @default 0
             */
            macro_unavailable_excluded: number;
        };
        /** RecommendationRequest */
        RecommendationRequest: {
            /**
             * Input Type
             * @default text
             * @enum {string}
             */
            input_type: "text" | "image" | "manual" | "mixed";
            /** Image Path */
            image_path?: string | null;
            /** Typed Ingredients */
            typed_ingredients?: string | null;
            /** Confirmed Inventory */
            confirmed_inventory?: components["schemas"]["ConfirmedIngredient"][] | null;
            user_profile: components["schemas"]["UserProfile"];
            /** Cuisine Preference */
            cuisine_preference?: string | null;
            /** Meal Type */
            meal_type?: string | null;
        };
        /** RecommendationResponse */
        RecommendationResponse: {
            /** Recommendations */
            recommendations?: components["schemas"]["MealRecommendation"][];
            /** Shopping List */
            shopping_list?: components["schemas"]["ShoppingItem"][];
            /** Rejected Recipes */
            rejected_recipes?: components["schemas"]["RejectedRecipe"][];
            /** Inventory Observations */
            inventory_observations?: components["schemas"]["InventoryObservation"][];
            /** Debug Trace */
            debug_trace?: string[];
            /** Errors */
            errors?: string[];
            taste_profile?: components["schemas"]["TasteProfile"] | null;
            /** Waste Nudges */
            waste_nudges?: components["schemas"]["WasteNudge"][];
        };
        /** ReindexLibraryResponse */
        ReindexLibraryResponse: {
            /** Indexed Count */
            indexed_count: number;
            /** Status */
            status: string;
        };
        /** RejectedRecipe */
        RejectedRecipe: {
            /** Recipe Id */
            recipe_id: string;
            /** Title */
            title: string;
            /** Reason */
            reason: string;
        };
        /**
         * SaveRecipeCandidatesRequest
         * @description The `/library/save` request body. No `user_id` field -- see
         *     `RecipeDiscoveryRequest`'s docstring.
         */
        SaveRecipeCandidatesRequest: {
            /** Selected Candidates */
            selected_candidates?: components["schemas"]["RecipeCandidate"][];
        };
        /** SaveRecipeCandidatesResponse */
        SaveRecipeCandidatesResponse: {
            /** Saved Recipe Ids */
            saved_recipe_ids?: string[];
            /** Skipped Duplicates */
            skipped_duplicates?: string[];
            /** Failed Candidates */
            failed_candidates?: {
                [key: string]: unknown;
            }[];
            /** Debug Trace */
            debug_trace?: string[];
        };
        /**
         * ShareCreateRequest
         * @description Body for POST /share.
         *
         *     `plan_type` selects exactly one of the five optional fields below --
         *     the matching object the (authenticated) client already holds in its own
         *     UI state. This is intentionally NOT the wire-level shape that gets
         *     persisted: `app.services.share_service.create_share` maps whichever
         *     field is populated through the server-side allowlist functions above
         *     before anything is written to `SharedPlan.content` -- the client object
         *     is read from, never echoed or persisted verbatim (see that module's
         *     docstring for why).
         */
        ShareCreateRequest: {
            /**
             * Plan Type
             * @enum {string}
             */
            plan_type: "recipe" | "day" | "batch" | "week" | "shopping_list";
            recipe?: components["schemas"]["Recipe"] | null;
            day_plan?: components["schemas"]["DayPlan"] | null;
            batch_plan?: components["schemas"]["BatchPlan"] | null;
            weekly_plan?: components["schemas"]["WeeklyPlan"] | null;
            /** Shopping List */
            shopping_list?: components["schemas"]["ShoppingItem"][] | null;
        };
        /**
         * ShareCreateResponse
         * @description Response for POST /share. Deliberately just the opaque id -- no
         *     hardcoded public hostname (see app.api.routes_share.create_share);
         *     the frontend composes the full share URL itself.
         */
        ShareCreateResponse: {
            /** Share Id */
            share_id: string;
        };
        /**
         * SharedPlanView
         * @description Response for GET /share/{id} -- the ONLY thing an anonymous caller
         *     ever receives. Never the ORM row, never `owner_user_id`, never any field
         *     not declared here.
         */
        SharedPlanView: {
            /**
             * Plan Type
             * @enum {string}
             */
            plan_type: "recipe" | "day" | "batch" | "week" | "shopping_list";
            /** Content */
            content: components["schemas"]["PublicRecipe"] | components["schemas"]["PublicDayPlan"] | components["schemas"]["PublicBatchPlan"] | components["schemas"]["PublicWeeklyPlan"] | components["schemas"]["ShoppingItem"][];
            /** Disclaimer */
            disclaimer: string;
        };
        /** ShoppingItem */
        ShoppingItem: {
            /** Name */
            name: string;
            /** Quantity */
            quantity?: string | null;
            /** Amount */
            amount?: number | null;
            /** Unit */
            unit?: string | null;
            /** Reason */
            reason?: string | null;
        };
        /**
         * ShoppingListRequest
         * @description Wire contract for POST /plan/shopping-list (roadmap item B4).
         *
         *     `plan` is an already-assembled DayPlan (its recipe_ids were already
         *     safety-cleared by /plan/day's constraint_engine.validate_recipe pass --
         *     this endpoint makes no new safety decision, it only does quantity
         *     arithmetic, so it takes no user_profile and never re-filters). `inventory`
         *     is the pantry to reconcile against, same shape POST /plan/day's caller
         *     already has on hand from app.api.routes_inventory.
         */
        ShoppingListRequest: {
            plan: components["schemas"]["DayPlan"];
            /** Inventory */
            inventory?: components["schemas"]["ConfirmedIngredient"][];
        };
        /** ShoppingListResponse */
        ShoppingListResponse: {
            /** Shopping List */
            shopping_list?: components["schemas"]["ShoppingItem"][];
        };
        /**
         * SuggestedRecipe
         * @description One corpus recipe suggested as a way to use an expiring ingredient
         *     before it goes bad. Deliberately minimal -- just enough to link/display,
         *     not a full `app.schemas.recipe.Recipe` (the caller already has the full
         *     corpus if it needs more).
         */
        SuggestedRecipe: {
            /** Recipe Id */
            recipe_id: string;
            /** Title */
            title: string;
        };
        /**
         * TasteProfile
         * @description Generalizing taste-profile signal derived from a user's own feedback
         *     history (Phase 3: visible personalization loop -- see
         *     app.services.memory_service.derive_taste_profile for the derivation).
         *
         *     Ranking/UX only, never a safety signal: this is deliberately blind to,
         *     and never consulted by, app.services.constraint_engine. Both fields stay
         *     empty (never populated from a single data point) until the deriving
         *     user has enough feedback history to clear the minimum-sample-size floor
         *     documented alongside derive_taste_profile -- an empty list here always
         *     means "no signal yet", never "fabricated from one recipe".
         */
        TasteProfile: {
            /** Avoided Ingredients */
            avoided_ingredients?: string[];
            /** Preferred Cuisines */
            preferred_cuisines?: string[];
        };
        /** UserProfile */
        UserProfile: {
            /**
             * User Id
             * @default demo_user
             */
            user_id: string;
            /** Allergies */
            allergies?: string[];
            /** Disliked Ingredients */
            disliked_ingredients?: string[];
            /** Diet Type */
            diet_type?: string | null;
            /** Preferred Cuisines */
            preferred_cuisines?: string[];
            macro_targets?: components["schemas"]["MacroTargets"];
            /** Max Cook Time Min */
            max_cook_time_min?: number | null;
        };
        /** UserRecipeLibraryResponse */
        UserRecipeLibraryResponse: {
            /** Recipes */
            recipes?: components["schemas"]["Recipe"][];
        };
        /** ValidateRecipeToolRequest */
        ValidateRecipeToolRequest: {
            recipe: components["schemas"]["Recipe"];
            user_profile: components["schemas"]["UserProfile"];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** ValidationResult */
        ValidationResult: {
            /** Is Valid */
            is_valid: boolean;
            /** Rejection Reason */
            rejection_reason?: string | null;
        };
        /**
         * WasteNudge
         * @description One expiring-soon inventory ingredient plus up to a few corpus
         *     recipes that use it. `days_until_expiry` is the same rough,
         *     flat-shelf-life-window estimate as
         *     `app.schemas.inventory.ConfirmedIngredient.days_until_expiry` -- None
         *     when the ingredient's `expires_soon` flag was set explicitly rather than
         *     derived from a logged `purchase_date` (no date to estimate from).
         *     `suggested_recipes` can be empty (the ingredient is expiring but no
         *     corpus recipe uses it) -- an empty list is still a valid, honest nudge,
         *     never suppressed here; the frontend template decides how to phrase that.
         */
        WasteNudge: {
            /** Ingredient Name */
            ingredient_name: string;
            /** Days Until Expiry */
            days_until_expiry?: number | null;
            /** Suggested Recipes */
            suggested_recipes?: components["schemas"]["SuggestedRecipe"][];
        };
        /**
         * WeeklyPlan
         * @description Result of `app.services.weekly_planner.assemble_week` (roadmap item,
         *     Phase 4 item 2: full weekly meal-plan solver).
         *
         *     THIS IS A THIN COMPOSITION OF B3 (`app.services.day_planner`), not a new
         *     solver: `days` is exactly `app.services.day_planner.assemble_day_plan`
         *     called once per day, same target every time -- see that module's own
         *     docstring for the algorithm, tolerance, and trust boundary, all reused
         *     unchanged.
         *
         *     KNOWN, DELIBERATE, HONEST LIMITATION -- state loudly, do not bury:
         *     because recipe selection is macro-only and pantry-independent (macros
         *     don't depend on pantry state, so there is no day-to-day pantry-depletion
         *     state carried between calls), and the trusted pool is tiny (~15 recipes
         *     as of the A3 corpus -- see `app.services.day_planner`'s "CRUX FINDING"),
         *     every one of `days` calls to `assemble_day_plan` receives the exact same
         *     candidates and the exact same target, and is therefore fully
         *     deterministic. **All `days` entries in `WeeklyPlan.days` will typically
         *     come out IDENTICAL** (the same day-plan repeated `days` times). This is
         *     an honest artifact of the corpus's current grounding coverage, not a
         *     bug in this module -- see docs/BACKLOG.md ("Weekly meal-plan solver")
         *     for the pre-registered "day-to-day variety" follow-up.
         *
         *     `pantry_utilization` is REPORTED FOR VISIBILITY ONLY -- it is never
         *     optimized, maximized, or used to gate/select which recipes are chosen.
         *     It is the fraction of the week's total (quantity-comparable) ingredient
         *     need that the supplied pantry (`ConfirmedIngredient` inventory) covers,
         *     computed with the same `app.utils.unit_converter.to_grams` arithmetic
         *     `app.services.procurement_service` uses. Ingredients whose need or
         *     pantry quantity can't be resolved to grams (`to_grams` returns `None`)
         *     are excluded from BOTH the numerator and denominator -- never silently
         *     treated as 0% or 100% covered -- and counted separately in
         *     `uncompared_ingredient_count` (mirrors `procurement_service`'s own
         *     `present_uncompared` honesty pattern).
         */
        WeeklyPlan: {
            /** Days */
            days?: components["schemas"]["DayPlan"][];
            /** Pantry Utilization */
            pantry_utilization: number;
            /** Uncompared Ingredient Count */
            uncompared_ingredient_count: number;
            /** Trusted Pool Size */
            trusted_pool_size: number;
        };
        /**
         * WeeklyPlanRequest
         * @description Wire contract for POST /plan/week.
         *
         *     `user_profile.macro_targets` is used as the SAME target for every day
         *     of the week (mirrors `DayPlanRequest`'s own use of
         *     `user_profile.macro_targets` -- see `app/schemas/day_plan.py`).
         *
         *     No `candidate_recipe_ids` field, deliberately -- same reasoning as
         *     `DayPlanRequest`/`BatchPlanRequest`: the endpoint always starts from the
         *     full corpus and applies `app.services.constraint_engine.validate_recipe`
         *     itself (see `app.api.routes_day_planner.plan_week`) -- letting a client
         *     hand in a pre-filtered candidate list would open a second,
         *     client-controlled path around that mandatory safety filter.
         *
         *     `inventory` mirrors `BatchPlanRequest.inventory` in shape: this endpoint
         *     builds the week's ONE CONSOLIDATED shopping list itself (via
         *     `app.services.procurement_service.build_shopping_list_for_items`, pooling
         *     every day's `PlanItem`s together) as part of the same request/response
         *     round trip, and also feeds `pantry_utilization`. Defaults to empty (no
         *     pantry reconciliation, full quantities listed, 0.0 utilization) when
         *     omitted.
         */
        WeeklyPlanRequest: {
            user_profile: components["schemas"]["UserProfile"];
            /**
             * Days
             * @default 7
             */
            days: number;
            /**
             * Max Per Recipe
             * @default 2
             */
            max_per_recipe: number;
            /** Inventory */
            inventory?: components["schemas"]["ConfirmedIngredient"][];
        };
        /** WeeklyPlanResponse */
        WeeklyPlanResponse: {
            plan: components["schemas"]["WeeklyPlan"];
            /** Rejected Recipes */
            rejected_recipes?: components["schemas"]["RejectedRecipe"][];
            /** Shopping List */
            shopping_list?: components["schemas"]["ShoppingItem"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    api_info_api_info_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    extract_inventory_inventory_extract_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": components["schemas"]["Body_extract_inventory_inventory_extract_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InventoryObservation"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_recipe_recipes__recipe_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recipe_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Recipe"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_recipes_recipes_search_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Session-Token"?: string | null;
                "X-Requested-With"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecipeSearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipeSearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    recommend_recipes_recipes_recommend_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Session-Token"?: string | null;
                "X-Requested-With"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecommendationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecommendationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_detailed_instructions_recipes_instructions_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Session-Token"?: string | null;
                "X-Requested-With"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DetailedInstructionsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetailedInstructionsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    discover_recipes_library_discover_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Session-Token"?: string | null;
                "X-Requested-With"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecipeDiscoveryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipeDiscoveryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_recipe_candidates_library_save_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Session-Token"?: string | null;
                "X-Requested-With"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveRecipeCandidatesRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SaveRecipeCandidatesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reindex_recipe_library_library_reindex_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Session-Token"?: string | null;
                "X-Requested-With"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReindexLibraryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_user_recipe_library_library_get: {
        parameters: {
            query?: never;
            header?: {
                "X-Session-Token"?: string | null;
                "X-Requested-With"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRecipeLibraryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_user_recipe_library__recipe_id__delete: {
        parameters: {
            query?: never;
            header?: {
                "X-Session-Token"?: string | null;
                "X-Requested-With"?: string | null;
            };
            path: {
                recipe_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteRecipeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_feedback_feedback_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Session-Token"?: string | null;
                "X-Requested-With"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    plan_day_plan_day_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DayPlanRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DayPlanResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    plan_batch_plan_batch_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BatchPlanRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchPlanResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    plan_week_plan_week_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WeeklyPlanRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeeklyPlanResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    plan_shopping_list_plan_shopping_list_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ShoppingListRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShoppingListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    validate_recipe_tool_tools_validate_recipe_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ValidateRecipeToolRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    check_allergen_tool_tools_check_allergen_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckAllergenToolRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckAllergenToolResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    check_diet_violation_tool_tools_check_diet_violation_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckDietViolationToolRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckDietViolationToolResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    derive_allergen_labels_tool_tools_derive_allergen_labels_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeriveAllergenLabelsToolRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeriveAllergenLabelsToolResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_share_link_share_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Session-Token"?: string | null;
                "X-Requested-With"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ShareCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShareCreateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_share_view_share__share_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                share_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SharedPlanView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mint_or_validate_session_session_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
