"""baseline schema

ROADMAP.md Phase 5, Step 5.1: the first Alembic revision. Represents the
full schema as it existed on 2026-07-28 (Feedback, SessionMemory,
UserSavedRecipe, SharedPlan, LLMCall, LLMCacheEntry -- see
`app/data/models.py`), generated via `alembic revision --autogenerate`
against a fresh, empty database. Before this revision, schema management
was entirely `Base.metadata.create_all` (see `app/data/db.py`'s
`init_db`); from here on, a non-sqlite `DATABASE_URL` (Postgres/Neon) is
managed exclusively through `alembic upgrade head`.

Revision ID: 0001
Revises:
Create Date: 2026-07-28 20:19:45.955247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('recipe_id', sa.String(length=128), nullable=False),
    sa.Column('feedback_type', sa.String(length=32), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_feedback_type'), 'feedback', ['feedback_type'], unique=False)
    op.create_index(op.f('ix_feedback_id'), 'feedback', ['id'], unique=False)
    op.create_index(op.f('ix_feedback_recipe_id'), 'feedback', ['recipe_id'], unique=False)
    op.create_index(op.f('ix_feedback_user_id'), 'feedback', ['user_id'], unique=False)
    op.create_table('llm_cache_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cache_key', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('purpose', sa.String(length=64), nullable=False),
    sa.Column('response_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_cache_entries_cache_key'), 'llm_cache_entries', ['cache_key'], unique=True)
    op.create_index(op.f('ix_llm_cache_entries_created_at'), 'llm_cache_entries', ['created_at'], unique=False)
    op.create_index(op.f('ix_llm_cache_entries_expires_at'), 'llm_cache_entries', ['expires_at'], unique=False)
    op.create_index(op.f('ix_llm_cache_entries_id'), 'llm_cache_entries', ['id'], unique=False)
    op.create_index(op.f('ix_llm_cache_entries_model'), 'llm_cache_entries', ['model'], unique=False)
    op.create_index(op.f('ix_llm_cache_entries_provider'), 'llm_cache_entries', ['provider'], unique=False)
    op.create_index(op.f('ix_llm_cache_entries_purpose'), 'llm_cache_entries', ['purpose'], unique=False)
    op.create_table('llm_calls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=True),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('purpose', sa.String(length=64), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('fallback_used', sa.Boolean(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('retries', sa.Integer(), nullable=False),
    sa.Column('parse_fallback', sa.Boolean(), nullable=False),
    sa.Column('cache_hit', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_calls_created_at'), 'llm_calls', ['created_at'], unique=False)
    op.create_index(op.f('ix_llm_calls_id'), 'llm_calls', ['id'], unique=False)
    op.create_index(op.f('ix_llm_calls_model'), 'llm_calls', ['model'], unique=False)
    op.create_index(op.f('ix_llm_calls_provider'), 'llm_calls', ['provider'], unique=False)
    op.create_index(op.f('ix_llm_calls_purpose'), 'llm_calls', ['purpose'], unique=False)
    op.create_index(op.f('ix_llm_calls_run_id'), 'llm_calls', ['run_id'], unique=False)
    op.create_index(op.f('ix_llm_calls_user_id'), 'llm_calls', ['user_id'], unique=False)
    op.create_table('session_memory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_memory_id'), 'session_memory', ['id'], unique=False)
    op.create_index(op.f('ix_session_memory_user_id'), 'session_memory', ['user_id'], unique=False)
    op.create_table('shared_plans',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('plan_type', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('owner_user_id', sa.String(length=128), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shared_plans_id'), 'shared_plans', ['id'], unique=False)
    op.create_index(op.f('ix_shared_plans_is_active'), 'shared_plans', ['is_active'], unique=False)
    op.create_index(op.f('ix_shared_plans_owner_user_id'), 'shared_plans', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_shared_plans_plan_type'), 'shared_plans', ['plan_type'], unique=False)
    op.create_table('user_saved_recipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('cuisine', sa.String(length=64), nullable=True),
    sa.Column('meal_type', sa.String(length=64), nullable=True),
    sa.Column('recipe_json', sa.Text(), nullable=False),
    sa.Column('source_type', sa.String(length=64), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('image_path', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'recipe_id', name='uq_user_saved_recipes_user_recipe')
    )
    op.create_index(op.f('ix_user_saved_recipes_cuisine'), 'user_saved_recipes', ['cuisine'], unique=False)
    op.create_index(op.f('ix_user_saved_recipes_id'), 'user_saved_recipes', ['id'], unique=False)
    op.create_index(op.f('ix_user_saved_recipes_is_active'), 'user_saved_recipes', ['is_active'], unique=False)
    op.create_index(op.f('ix_user_saved_recipes_meal_type'), 'user_saved_recipes', ['meal_type'], unique=False)
    op.create_index(op.f('ix_user_saved_recipes_recipe_id'), 'user_saved_recipes', ['recipe_id'], unique=False)
    op.create_index(op.f('ix_user_saved_recipes_title'), 'user_saved_recipes', ['title'], unique=False)
    op.create_index(op.f('ix_user_saved_recipes_user_id'), 'user_saved_recipes', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_saved_recipes_user_id'), table_name='user_saved_recipes')
    op.drop_index(op.f('ix_user_saved_recipes_title'), table_name='user_saved_recipes')
    op.drop_index(op.f('ix_user_saved_recipes_recipe_id'), table_name='user_saved_recipes')
    op.drop_index(op.f('ix_user_saved_recipes_meal_type'), table_name='user_saved_recipes')
    op.drop_index(op.f('ix_user_saved_recipes_is_active'), table_name='user_saved_recipes')
    op.drop_index(op.f('ix_user_saved_recipes_id'), table_name='user_saved_recipes')
    op.drop_index(op.f('ix_user_saved_recipes_cuisine'), table_name='user_saved_recipes')
    op.drop_table('user_saved_recipes')
    op.drop_index(op.f('ix_shared_plans_plan_type'), table_name='shared_plans')
    op.drop_index(op.f('ix_shared_plans_owner_user_id'), table_name='shared_plans')
    op.drop_index(op.f('ix_shared_plans_is_active'), table_name='shared_plans')
    op.drop_index(op.f('ix_shared_plans_id'), table_name='shared_plans')
    op.drop_table('shared_plans')
    op.drop_index(op.f('ix_session_memory_user_id'), table_name='session_memory')
    op.drop_index(op.f('ix_session_memory_id'), table_name='session_memory')
    op.drop_table('session_memory')
    op.drop_index(op.f('ix_llm_calls_user_id'), table_name='llm_calls')
    op.drop_index(op.f('ix_llm_calls_run_id'), table_name='llm_calls')
    op.drop_index(op.f('ix_llm_calls_purpose'), table_name='llm_calls')
    op.drop_index(op.f('ix_llm_calls_provider'), table_name='llm_calls')
    op.drop_index(op.f('ix_llm_calls_model'), table_name='llm_calls')
    op.drop_index(op.f('ix_llm_calls_id'), table_name='llm_calls')
    op.drop_index(op.f('ix_llm_calls_created_at'), table_name='llm_calls')
    op.drop_table('llm_calls')
    op.drop_index(op.f('ix_llm_cache_entries_purpose'), table_name='llm_cache_entries')
    op.drop_index(op.f('ix_llm_cache_entries_provider'), table_name='llm_cache_entries')
    op.drop_index(op.f('ix_llm_cache_entries_model'), table_name='llm_cache_entries')
    op.drop_index(op.f('ix_llm_cache_entries_id'), table_name='llm_cache_entries')
    op.drop_index(op.f('ix_llm_cache_entries_expires_at'), table_name='llm_cache_entries')
    op.drop_index(op.f('ix_llm_cache_entries_created_at'), table_name='llm_cache_entries')
    op.drop_index(op.f('ix_llm_cache_entries_cache_key'), table_name='llm_cache_entries')
    op.drop_table('llm_cache_entries')
    op.drop_index(op.f('ix_feedback_user_id'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_recipe_id'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_id'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_feedback_type'), table_name='feedback')
    op.drop_table('feedback')
    # ### end Alembic commands ###
