"""rate limit hits table

ROADMAP.md Phase 5, Step 5.2: backs `app.services.rate_limiter.
PostgresRateLimiter`, the shared cross-replica rate limiter that clears
the second half of the `max-replicas=1` blocker (the first half, the
embedded single-writer Chroma store, is addressed by revision 0002's
pgvector backend). Unlike 0002, this table lives on `Base.metadata`
normally (see `app.data.models.RateLimitHit`) -- it's a plain
String/DateTime table with no exotic column types, so it needs no
dialect guard or `include_object` exclusion the way pgvector's `vector`
column did.

Revision ID: 0003
Revises: 0002
Create Date: 2026-07-29 10:20:36.904472

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0003'
down_revision: str | None = '0002'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rate_limit_hits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=256), nullable=False),
    sa.Column('hit_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rate_limit_hits_id'), 'rate_limit_hits', ['id'], unique=False)
    op.create_index(
        'ix_rate_limit_hits_key_hit_at', 'rate_limit_hits', ['key', 'hit_at'], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_rate_limit_hits_key_hit_at', table_name='rate_limit_hits')
    op.drop_index(op.f('ix_rate_limit_hits_id'), table_name='rate_limit_hits')
    op.drop_table('rate_limit_hits')
    # ### end Alembic commands ###
