"""graph runs table

ROADMAP.md Phase 3, Step 3.2: `thread_id -> owner_user_id` ownership
mapping for the checkpointed HITL recommend graph (see
`app.data.models.GraphRun`). Distinct from LangGraph's own checkpoint
tables, which are created by `SqliteSaver`/`PostgresSaver.setup()` and
deliberately kept OUTSIDE this app's Alembic migrations -- see
`app.graph.builder._select_checkpointer`'s docstring.

Revision ID: 0004
Revises: 0003
Create Date: 2026-07-29 11:54:15.407348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0004'
down_revision: Union[str, None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('graph_runs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('owner_user_id', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_graph_runs_id'), 'graph_runs', ['id'], unique=False)
    op.create_index(op.f('ix_graph_runs_owner_user_id'), 'graph_runs', ['owner_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_graph_runs_owner_user_id'), table_name='graph_runs')
    op.drop_index(op.f('ix_graph_runs_id'), table_name='graph_runs')
    op.drop_table('graph_runs')
    # ### end Alembic commands ###
